"""added user and employee references on inventory movements and audit logs

Revision ID: 09b482db6e82
Revises: be8e9463ee6b
Create Date: 2026-03-15 10:37:51.927057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b482db6e82'
down_revision: Union[str, Sequence[str], None] = 'be8e9463ee6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_user_id', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_employee_id', sa.String(length=50), nullable=True))
    op.add_column('inventory_movements', sa.Column('actor_user_id', sa.String(length=50), nullable=True))
    op.add_column('inventory_movements', sa.Column('actor_employee_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_movements', 'actor_employee_id')
    op.drop_column('inventory_movements', 'actor_user_id')
    op.drop_column('audit_logs', 'actor_employee_id')
    op.drop_column('audit_logs', 'actor_user_id')
    # ### end Alembic commands ###
