"""refine_requested_items_with_borrow_link

Revision ID: 0c9ddb2401bd
Revises: 9bf60f8c5476
Create Date: 2026-03-14 17:36:44.741081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9ddb2401bd'
down_revision: Union[str, Sequence[str], None] = '9bf60f8c5476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requested_items', sa.Column('borrow_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_requested_items_borrow_id'), 'requested_items', ['borrow_id'], unique=False)
    op.create_foreign_key(None, 'requested_items', 'borrow_requests', ['borrow_id'], ['borrow_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requested_items', type_='foreignkey')
    op.drop_index(op.f('ix_requested_items_borrow_id'), table_name='requested_items')
    op.drop_column('requested_items', 'borrow_id')
    # ### end Alembic commands ###
