"""add closed fields to borrow requests

Revision ID: 0ef47b079095
Revises: 63f92cef5527
Create Date: 2026-03-18 22:20:20.333225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef47b079095'
down_revision: Union[str, Sequence[str], None] = '63f92cef5527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('borrow_requests', sa.Column('closed_by', sa.Uuid(), nullable=True))
    op.add_column('borrow_requests', sa.Column('close_reason', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'borrow_requests', 'users', ['closed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrow_requests', type_='foreignkey')
    op.drop_column('borrow_requests', 'close_reason')
    op.drop_column('borrow_requests', 'closed_by')
    op.drop_column('borrow_requests', 'closed_at')
    # ### end Alembic commands ###
