"""rename_due_at_and_cleanup_metadata

Revision ID: 103ff9835cb9
Revises: 92ebc57ffde0
Create Date: 2026-03-16 19:56:02.697085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '103ff9835cb9'
down_revision: Union[str, Sequence[str], None] = '92ebc57ffde0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('return_at', sa.DateTime(), nullable=True))
    op.drop_column('borrow_requests', 'store_name')
    op.drop_column('borrow_requests', 'due_at')
    op.drop_column('borrow_requests', 'team_name')
    op.drop_column('borrow_requests', 'location_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('borrow_requests', sa.Column('team_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('borrow_requests', sa.Column('due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('borrow_requests', sa.Column('store_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('borrow_requests', 'return_at')
    # ### end Alembic commands ###
