"""rename_borrow_id_to_request_id

Revision ID: 19e8f865fa7c
Revises: 103ff9835cb9
Create Date: 2026-03-16 20:26:36.039120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e8f865fa7c'
down_revision: Union[str, Sequence[str], None] = '103ff9835cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('request_id', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_borrow_requests_borrow_id'), table_name='borrow_requests')
    op.create_index(op.f('ix_borrow_requests_request_id'), 'borrow_requests', ['request_id'], unique=True)
    op.drop_column('borrow_requests', 'borrow_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('borrow_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_borrow_requests_request_id'), table_name='borrow_requests')
    op.create_index(op.f('ix_borrow_requests_borrow_id'), 'borrow_requests', ['borrow_id'], unique=True)
    op.drop_column('borrow_requests', 'request_id')
    # ### end Alembic commands ###
