"""add_batch_uuid_to_movement

Revision ID: 1c43501fcf5b
Revises: 7ed232439717
Create Date: 2026-03-18 09:03:46.601346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c43501fcf5b'
down_revision: Union[str, Sequence[str], None] = '7ed232439717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('batch_uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_inventory_movements_batch_uuid'), 'inventory_movements', ['batch_uuid'], unique=False)
    op.create_foreign_key(None, 'inventory_movements', 'inventory_batches', ['batch_uuid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movements_batch_uuid'), table_name='inventory_movements')
    op.drop_column('inventory_movements', 'batch_uuid')
    # ### end Alembic commands ###
