"""add_system_column_to_config_tables

Revision ID: 217aa8ea67d6
Revises: 5346c19e67fb
Create Date: 2026-03-29 12:29:15.427033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217aa8ea67d6'
down_revision: Union[str, Sequence[str], None] = '5346c19e67fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column('admin_configurations', sa.Column('system', sa.String(length=50), nullable=True))
    op.add_column('auth_configurations', sa.Column('system', sa.String(length=50), nullable=True))
    op.add_column('borrower_configurations', sa.Column('system', sa.String(length=50), nullable=True))
    op.add_column('inventory_configurations', sa.Column('system', sa.String(length=50), nullable=True))

    # Update existing rows
    op.execute("UPDATE admin_configurations SET system = 'admin'")
    op.execute("UPDATE auth_configurations SET system = 'auth'")
    op.execute("UPDATE borrower_configurations SET system = 'borrower'")
    op.execute("UPDATE inventory_configurations SET system = 'inventory'")

    # Set as NOT NULL
    op.alter_column('admin_configurations', 'system', nullable=False)
    op.alter_column('auth_configurations', 'system', nullable=False)
    op.alter_column('borrower_configurations', 'system', nullable=False)
    op.alter_column('inventory_configurations', 'system', nullable=False)

    # Create indexes
    op.create_index(op.f('ix_admin_configurations_system'), 'admin_configurations', ['system'], unique=False)
    op.create_index(op.f('ix_auth_configurations_system'), 'auth_configurations', ['system'], unique=False)
    op.create_index(op.f('ix_borrower_configurations_system'), 'borrower_configurations', ['system'], unique=False)
    op.create_index(op.f('ix_inventory_configurations_system'), 'inventory_configurations', ['system'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_configurations_system'), table_name='inventory_configurations')
    op.drop_column('inventory_configurations', 'system')
    op.drop_index(op.f('ix_borrower_configurations_system'), table_name='borrower_configurations')
    op.drop_column('borrower_configurations', 'system')
    op.drop_index(op.f('ix_auth_configurations_system'), table_name='auth_configurations')
    op.drop_column('auth_configurations', 'system')
    op.drop_index(op.f('ix_admin_configurations_system'), table_name='admin_configurations')
    op.drop_column('admin_configurations', 'system')
    # ### end Alembic commands ###
