"""adding backup tracking table

Revision ID: 38ffd42fbb3e
Revises: 7a057e68a1ff
Create Date: 2026-03-14 20:26:05.739454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ffd42fbb3e'
down_revision: Union[str, Sequence[str], None] = '7a057e68a1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('backup_id', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_runs_backup_id'), 'backup_runs', ['backup_id'], unique=True)
    op.create_index(op.f('ix_backup_runs_triggered_by'), 'backup_runs', ['triggered_by'], unique=False)
    op.create_table('backup_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('artifact_id', sa.String(length=20), nullable=False),
    sa.Column('backup_run_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('file_path_or_key', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('verified_restore', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['backup_run_id'], ['backup_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_artifacts_artifact_id'), 'backup_artifacts', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_backup_artifacts_backup_run_id'), 'backup_artifacts', ['backup_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_artifacts_backup_run_id'), table_name='backup_artifacts')
    op.drop_index(op.f('ix_backup_artifacts_artifact_id'), table_name='backup_artifacts')
    op.drop_table('backup_artifacts')
    op.drop_index(op.f('ix_backup_runs_triggered_by'), table_name='backup_runs')
    op.drop_index(op.f('ix_backup_runs_backup_id'), table_name='backup_runs')
    op.drop_table('backup_runs')
    # ### end Alembic commands ###
