"""config tables for inventory, borrowers, auth

Revision ID: 3f46d2ceaae4
Revises: d701324a60cc
Create Date: 2026-03-16 12:08:46.012651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f46d2ceaae4'
down_revision: Union[str, Sequence[str], None] = 'd701324a60cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'category', name='uq_auth_config_key_category')
    )
    op.create_index('ix_auth_config_category', 'auth_configurations', ['category'], unique=False)
    op.create_index(op.f('ix_auth_configurations_key'), 'auth_configurations', ['key'], unique=False)
    op.create_table('borrower_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'category', name='uq_borrower_config_key_category')
    )
    op.create_index('ix_borrower_config_category', 'borrower_configurations', ['category'], unique=False)
    op.create_index(op.f('ix_borrower_configurations_key'), 'borrower_configurations', ['key'], unique=False)
    op.create_table('inventory_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'category', name='uq_inventory_config_key_category')
    )
    op.create_index('ix_inventory_config_category', 'inventory_configurations', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_configurations_key'), 'inventory_configurations', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_configurations_key'), table_name='inventory_configurations')
    op.drop_index('ix_inventory_config_category', table_name='inventory_configurations')
    op.drop_table('inventory_configurations')
    op.drop_index(op.f('ix_borrower_configurations_key'), table_name='borrower_configurations')
    op.drop_index('ix_borrower_config_category', table_name='borrower_configurations')
    op.drop_table('borrower_configurations')
    op.drop_index(op.f('ix_auth_configurations_key'), table_name='auth_configurations')
    op.drop_index('ix_auth_config_category', table_name='auth_configurations')
    op.drop_table('auth_configurations')
    # ### end Alembic commands ###
