"""add borrower signature to borrow request

Revision ID: 3f60c5bc7806
Revises: c3d7f8a9e2b1
Create Date: 2026-04-09 09:20:50.390139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f60c5bc7806'
down_revision: Union[str, Sequence[str], None] = 'c3d7f8a9e2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('borrower_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_requests', 'borrower_signature')
    # ### end Alembic commands ###
