"""Add status field to InventoryItem

Revision ID: 5346c19e67fb
Revises: 60f8a7b77f1c
Create Date: 2026-03-21 21:13:15.472404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5346c19e67fb'
down_revision: Union[str, Sequence[str], None] = '60f8a7b77f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('status', sa.String(length=50), nullable=False, server_default='healthy'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'status')
    # ### end Alembic commands ###
