"""refactored borrower id to string

Revision ID: 5efc0e5dc4b7
Revises: 71fcaa97bacd
Create Date: 2026-03-12 14:24:29.283922

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5efc0e5dc4b7'
down_revision: Union[str, Sequence[str], None] = '71fcaa97bacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('borrow_requests_borrower_id_fkey'), 'borrow_requests', type_='foreignkey')
    op.alter_column('borrow_requests', 'borrower_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_foreign_key(None, 'borrow_requests', 'users', ['borrower_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrow_requests', type_='foreignkey')
    op.alter_column('borrow_requests', 'borrower_id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(op.f('borrow_requests_borrower_id_fkey'), 'borrow_requests', 'users', ['borrower_id'], ['id'])
    # ### end Alembic commands ###
