"""remove_internal_ref_from_units

Revision ID: 60f8a7b77f1c
Revises: ba019417db27
Create Date: 2026-03-20 10:17:00.288212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f8a7b77f1c'
down_revision: Union[str, Sequence[str], None] = 'ba019417db27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_units_internal_ref'), table_name='inventory_units')
    op.drop_column('inventory_units', 'internal_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_units', sa.Column('internal_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_inventory_units_internal_ref'), 'inventory_units', ['internal_ref'], unique=True)
    # ### end Alembic commands ###
