"""add description to inventory items batches and units

Revision ID: 63f92cef5527
Revises: 156f3c55b78e
Create Date: 2026-03-18 21:48:01.967249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f92cef5527'
down_revision: Union[str, Sequence[str], None] = '156f3c55b78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('inventory_batches', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('inventory_units', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_units', 'description')
    op.drop_column('inventory_batches', 'description')
    op.drop_column('inventory', 'description')
    # ### end Alembic commands ###
