"""added borrower subsystem tables

Revision ID: 71039f428438
Revises: 38ffd42fbb3e
Create Date: 2026-03-14 21:22:01.530850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71039f428438'
down_revision: Union[str, Sequence[str], None] = '38ffd42fbb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrower_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('borrower_id', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrower_sessions_borrower_id'), 'borrower_sessions', ['borrower_id'], unique=False)
    op.create_table('borrow_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('borrow_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role_in_request', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['borrow_id'], ['borrow_requests.borrow_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_participants_borrow_id'), 'borrow_participants', ['borrow_id'], unique=False)
    op.create_index(op.f('ix_borrow_participants_user_id'), 'borrow_participants', ['user_id'], unique=False)
    op.add_column('borrow_requests', sa.Column('request_channel', sa.String(length=50), nullable=False))
    op.add_column('borrow_requests', sa.Column('compliance_followup_required', sa.Boolean(), nullable=False))
    op.add_column('borrow_requests', sa.Column('compliance_followup_notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_requests', 'compliance_followup_notes')
    op.drop_column('borrow_requests', 'compliance_followup_required')
    op.drop_column('borrow_requests', 'request_channel')
    op.drop_index(op.f('ix_borrow_participants_user_id'), table_name='borrow_participants')
    op.drop_index(op.f('ix_borrow_participants_borrow_id'), table_name='borrow_participants')
    op.drop_table('borrow_participants')
    op.drop_index(op.f('ix_borrower_sessions_borrower_id'), table_name='borrower_sessions')
    op.drop_table('borrower_sessions')
    # ### end Alembic commands ###
