"""added partial unique indexes

Revision ID: 71fcaa97bacd
Revises: c35bbf63b580
Create Date: 2026-03-12 14:01:53.027018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71fcaa97bacd'
down_revision: Union[str, Sequence[str], None] = 'c35bbf63b580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_active_borrow_request', 'borrow_requests', ['borrower_id', 'item_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'approved', 'released') AND is_deleted IS FALSE"))
    op.create_index('ix_inventory_item_name_active', 'inventory', ['name', 'category'], unique=True, postgresql_where=sa.text('is_deleted IS FALSE'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index('ix_user_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('is_deleted IS FALSE'))
    op.create_index('ix_user_username_active', 'users', ['username'], unique=True, postgresql_where=sa.text('is_deleted IS FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username_active', table_name='users', postgresql_where=sa.text('is_deleted IS FALSE'))
    op.drop_index('ix_user_email_active', table_name='users', postgresql_where=sa.text('is_deleted IS FALSE'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_inventory_item_name_active', table_name='inventory', postgresql_where=sa.text('is_deleted IS FALSE'))
    op.drop_index('ix_active_borrow_request', table_name='borrow_requests', postgresql_where=sa.text("status IN ('pending', 'approved', 'released') AND is_deleted IS FALSE"))
    # ### end Alembic commands ###
