"""added human readable audit_id in audit logs table

Revision ID: 7a057e68a1ff
Revises: 41a8ed4ffada
Create Date: 2026-03-14 19:58:00.194062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a057e68a1ff'
down_revision: Union[str, Sequence[str], None] = '41a8ed4ffada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('audit_id', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'audit_id')
    # ### end Alembic commands ###
