"""added_inventory_batches_table

Revision ID: 7ed232439717
Revises: 0306b0ba129b
Create Date: 2026-03-18 09:02:27.077226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed232439717'
down_revision: Union[str, Sequence[str], None] = '0306b0ba129b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('inventory_uuid', sa.Uuid(), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_uuid'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_batches_batch_id'), 'inventory_batches', ['batch_id'], unique=True)
    op.create_index(op.f('ix_inventory_batches_expiration_date'), 'inventory_batches', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_inventory_batches_inventory_uuid'), 'inventory_batches', ['inventory_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_batches_inventory_uuid'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_expiration_date'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_batch_id'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    # ### end Alembic commands ###
