"""add contact_number to users

Revision ID: 7f4819a67ecb
Revises: 20a938067f59
Create Date: 2026-03-14 15:36:29.228847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f4819a67ecb'
down_revision: Union[str, Sequence[str], None] = '20a938067f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_statuses_code'), table_name='inventory_statuses')
    op.drop_table('inventory_statuses')
    op.add_column('users', sa.Column('contact_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_number')
    op.create_table('inventory_statuses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('min_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_statuses_pkey'))
    )
    op.create_index(op.f('ix_inventory_statuses_code'), 'inventory_statuses', ['code'], unique=True)
    # ### end Alembic commands ###
