"""remove_legacy_borrow_fields

Revision ID: 92ebc57ffde0
Revises: c439df66839c
Create Date: 2026-03-16 19:26:12.147850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ebc57ffde0'
down_revision: Union[str, Sequence[str], None] = 'c439df66839c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_requests_item_uuid'), table_name='borrow_requests')
    op.drop_index(op.f('ix_active_borrow_request_uuid'), table_name='borrow_requests', postgresql_where="(((status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'released'::character varying])::text[])) AND (is_deleted IS FALSE))")
    op.create_index('ix_active_borrow_request_uuid', 'borrow_requests', ['borrower_uuid'], unique=True, postgresql_where=sa.text("status IN ('pending', 'approved', 'released') AND is_deleted IS FALSE"))
    op.drop_constraint(op.f('fk_borrow_requests_item_uuid_inventory_id'), 'borrow_requests', type_='foreignkey')
    op.drop_column('borrow_requests', 'item_uuid')
    op.drop_column('borrow_requests', 'qty_requested')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('qty_requested', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('borrow_requests', sa.Column('item_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_borrow_requests_item_uuid_inventory_id'), 'borrow_requests', 'inventory', ['item_uuid'], ['id'])
    op.drop_index('ix_active_borrow_request_uuid', table_name='borrow_requests', postgresql_where=sa.text("status IN ('pending', 'approved', 'released') AND is_deleted IS FALSE"))
    op.create_index(op.f('ix_active_borrow_request_uuid'), 'borrow_requests', ['borrower_uuid', 'item_uuid'], unique=True, postgresql_where="(((status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'released'::character varying])::text[])) AND (is_deleted IS FALSE))")
    op.create_index(op.f('ix_borrow_requests_item_uuid'), 'borrow_requests', ['item_uuid'], unique=False)
    # ### end Alembic commands ###
