"""phase_b_requested_items_and_warehouse

Revision ID: 9bf60f8c5476
Revises: d5210d4eb217
Create Date: 2026-03-14 17:08:25.240436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf60f8c5476'
down_revision: Union[str, Sequence[str], None] = 'd5210d4eb217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requested_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('request_ref', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('justification', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requested_items_request_ref'), 'requested_items', ['request_ref'], unique=True)
    op.create_index(op.f('ix_requested_items_requested_by'), 'requested_items', ['requested_by'], unique=False)
    op.create_table('warehouse_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('borrow_id', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('printable_payload_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['borrow_id'], ['borrow_requests.borrow_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_approvals_borrow_id'), 'warehouse_approvals', ['borrow_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_approvals_borrow_id'), table_name='warehouse_approvals')
    op.drop_table('warehouse_approvals')
    op.drop_index(op.f('ix_requested_items_requested_by'), table_name='requested_items')
    op.drop_index(op.f('ix_requested_items_request_ref'), table_name='requested_items')
    op.drop_table('requested_items')
    # ### end Alembic commands ###
