"""added request batch table

Revision ID: 9d08b17d0426
Revises: e4d2d73aefba
Create Date: 2026-03-19 11:02:23.263085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d08b17d0426'
down_revision: Union[str, Sequence[str], None] = 'e4d2d73aefba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow_request_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('borrow_batch_id', sa.String(length=50), nullable=False),
    sa.Column('borrow_uuid', sa.Uuid(), nullable=True),
    sa.Column('batch_uuid', sa.Uuid(), nullable=True),
    sa.Column('qty_assigned', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_uuid'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['borrow_uuid'], ['borrow_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_request_batches_batch_uuid'), 'borrow_request_batches', ['batch_uuid'], unique=False)
    op.create_index(op.f('ix_borrow_request_batches_borrow_batch_id'), 'borrow_request_batches', ['borrow_batch_id'], unique=True)
    op.create_index(op.f('ix_borrow_request_batches_borrow_uuid'), 'borrow_request_batches', ['borrow_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_request_batches_borrow_uuid'), table_name='borrow_request_batches')
    op.drop_index(op.f('ix_borrow_request_batches_borrow_batch_id'), table_name='borrow_request_batches')
    op.drop_index(op.f('ix_borrow_request_batches_batch_uuid'), table_name='borrow_request_batches')
    op.drop_table('borrow_request_batches')
    # ### end Alembic commands ###
