"""rename_warehouse_approval_field

Revision ID: acb602f1fe16
Revises: 19e8f865fa7c
Create Date: 2026-03-16 20:40:54.964762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb602f1fe16'
down_revision: Union[str, Sequence[str], None] = '19e8f865fa7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_approvals', sa.Column('request_id', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_warehouse_approvals_borrow_id'), table_name='warehouse_approvals')
    op.create_index(op.f('ix_warehouse_approvals_request_id'), 'warehouse_approvals', ['request_id'], unique=True)
    op.drop_column('warehouse_approvals', 'borrow_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_approvals', sa.Column('borrow_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_warehouse_approvals_request_id'), table_name='warehouse_approvals')
    op.create_index(op.f('ix_warehouse_approvals_borrow_id'), 'warehouse_approvals', ['borrow_id'], unique=True)
    op.drop_column('warehouse_approvals', 'request_id')
    # ### end Alembic commands ###
