"""implementing audit and consolodating users

Revision ID: bb2709b9e995
Revises: c7bef72d6bac
Create Date: 2026-03-14 19:07:46.242670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2709b9e995'
down_revision: Union[str, Sequence[str], None] = 'c7bef72d6bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.add_column('borrow_requests', sa.Column('involved_people', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('shift_type', sa.String(length=20), nullable=False))
    op.create_index('ix_user_employee_id_active', 'users', ['employee_id'], unique=True, postgresql_where=sa.text('is_deleted IS FALSE'))
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index('ix_user_employee_id_active', table_name='users', postgresql_where=sa.text('is_deleted IS FALSE'))
    op.drop_column('users', 'shift_type')
    op.drop_column('users', 'pin_hash')
    op.drop_column('users', 'employee_id')
    op.drop_column('borrow_requests', 'involved_people')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
