"""added constraints

Revision ID: be8e9463ee6b
Revises: f2d8856a7b55
Create Date: 2026-03-15 10:02:23.650932

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'be8e9463ee6b'
down_revision: Union[str, Sequence[str], None] = 'f2d8856a7b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_inventory_available_qty_positive",
        "inventory",
        "available_qty >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_inventory_available_qty_positive", "inventory")
    # ### end Alembic commands ###
