"""refactoring audit logs

Revision ID: c439df66839c
Revises: f0ead8945d4f
Create Date: 2026-03-16 17:14:25.308858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c439df66839c'
down_revision: Union[str, Sequence[str], None] = 'f0ead8945d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_logs_actor_id_users_id'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'actor_user_id')
    op.drop_column('audit_logs', 'actor_employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('actor_user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_audit_logs_actor_id_users_id'), 'audit_logs', 'users', ['actor_id'], ['id'])
    # ### end Alembic commands ###
