"""phase a: expand borrow requests and add events

Revision ID: c5c1dc1537aa
Revises: 7f4819a67ecb
Create Date: 2026-03-14 16:16:32.368764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c1dc1537aa'
down_revision: Union[str, Sequence[str], None] = '7f4819a67ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('transaction_ref', sa.String(length=50), nullable=False))
    op.add_column('borrow_requests', sa.Column('due_at', sa.DateTime(), nullable=True))
    op.add_column('borrow_requests', sa.Column('returned_on_time', sa.Boolean(), nullable=True))
    op.add_column('borrow_requests', sa.Column('release_employee_id', sa.String(length=50), nullable=True))
    op.add_column('borrow_requests', sa.Column('team_name', sa.String(length=100), nullable=True))
    op.add_column('borrow_requests', sa.Column('store_name', sa.String(length=100), nullable=True))
    op.add_column('borrow_requests', sa.Column('location_name', sa.String(length=100), nullable=True))
    op.add_column('borrow_requests', sa.Column('is_emergency', sa.Boolean(), nullable=False))
    op.add_column('borrow_requests', sa.Column('approval_channel', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_borrow_requests_transaction_ref'), 'borrow_requests', ['transaction_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_requests_transaction_ref'), table_name='borrow_requests')
    op.drop_column('borrow_requests', 'approval_channel')
    op.drop_column('borrow_requests', 'is_emergency')
    op.drop_column('borrow_requests', 'location_name')
    op.drop_column('borrow_requests', 'store_name')
    op.drop_column('borrow_requests', 'team_name')
    op.drop_column('borrow_requests', 'release_employee_id')
    op.drop_column('borrow_requests', 'returned_on_time')
    op.drop_column('borrow_requests', 'due_at')
    op.drop_column('borrow_requests', 'transaction_ref')
    # ### end Alembic commands ###
