"""implementing inventory tracking and movement tables

Revision ID: c7bef72d6bac
Revises: 0c9ddb2401bd
Create Date: 2026-03-14 17:48:10.639634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bef72d6bac'
down_revision: Union[str, Sequence[str], None] = '0c9ddb2401bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('inventory_id', sa.String(length=50), nullable=False),
    sa.Column('qty_change', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_inventory_id'), 'inventory_movements', ['inventory_id'], unique=False)
    op.create_table('inventory_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('inventory_id', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('internal_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_units_internal_ref'), 'inventory_units', ['internal_ref'], unique=True)
    op.create_index(op.f('ix_inventory_units_inventory_id'), 'inventory_units', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_units_serial_number'), 'inventory_units', ['serial_number'], unique=True)
    op.add_column('inventory', sa.Column('item_type', sa.String(length=50), nullable=False))
    op.add_column('inventory', sa.Column('classification', sa.String(length=100), nullable=True))
    op.add_column('inventory', sa.Column('is_trackable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'is_trackable')
    op.drop_column('inventory', 'classification')
    op.drop_column('inventory', 'item_type')
    op.drop_index(op.f('ix_inventory_units_serial_number'), table_name='inventory_units')
    op.drop_index(op.f('ix_inventory_units_inventory_id'), table_name='inventory_units')
    op.drop_index(op.f('ix_inventory_units_internal_ref'), table_name='inventory_units')
    op.drop_table('inventory_units')
    op.drop_index(op.f('ix_inventory_movements_inventory_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    # ### end Alembic commands ###
