"""Add EntrustedItem

Revision ID: d1661f27e114
Revises: 90b4bf4f0c67
Create Date: 2026-04-20 19:04:42.154615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1661f27e114'
down_revision: Union[str, Sequence[str], None] = '90b4bf4f0c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrusted_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('retention_tags', sa.JSON(), nullable=True),
    sa.Column('assignment_id', sa.String(length=50), nullable=False),
    sa.Column('unit_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('returned_by', sa.Uuid(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['returned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_uuid'], ['inventory_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrusted_items_assignment_id'), 'entrusted_items', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_entrusted_items_is_archived'), 'entrusted_items', ['is_archived'], unique=False)
    op.create_index(op.f('ix_entrusted_items_unit_uuid'), 'entrusted_items', ['unit_uuid'], unique=False)
    op.create_index(op.f('ix_entrusted_items_user_id'), 'entrusted_items', ['user_id'], unique=False)
    op.alter_column('borrow_requests', 'borrower_signature',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrow_requests', 'borrower_signature',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_entrusted_items_user_id'), table_name='entrusted_items')
    op.drop_index(op.f('ix_entrusted_items_unit_uuid'), table_name='entrusted_items')
    op.drop_index(op.f('ix_entrusted_items_is_archived'), table_name='entrusted_items')
    op.drop_index(op.f('ix_entrusted_items_assignment_id'), table_name='entrusted_items')
    op.drop_table('entrusted_items')
    # ### end Alembic commands ###
