"""normalizing config tables

Revision ID: d701324a60cc
Revises: f3a7e2c9d5b1
Create Date: 2026-03-16 12:02:42.988864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd701324a60cc'
down_revision: Union[str, Sequence[str], None] = 'f3a7e2c9d5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'category', name='uq_admin_settings_key_category')
    )
    op.create_index(op.f('ix_admin_configurations_key'), 'admin_configurations', ['key'], unique=False)
    op.create_index('ix_admin_settings_category', 'admin_configurations', ['category'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_uuid'), 'user_sessions', ['user_uuid'], unique=False)
    op.drop_index(op.f('ix_system_settings_category'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.alter_column('borrow_request_items', 'borrow_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('borrow_request_items', 'item_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_borrow_requests_received_by'), table_name='borrow_requests')
    op.drop_index(op.f('ix_borrow_requests_returned_by'), table_name='borrow_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_borrow_requests_returned_by'), 'borrow_requests', ['returned_by'], unique=False)
    op.create_index(op.f('ix_borrow_requests_received_by'), 'borrow_requests', ['received_by'], unique=False)
    op.alter_column('borrow_request_items', 'item_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('borrow_request_items', 'borrow_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey')),
    sa.UniqueConstraint('key', 'category', name=op.f('uq_system_settings_key_category'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_index(op.f('ix_system_settings_category'), 'system_settings', ['category'], unique=False)
    op.drop_index(op.f('ix_user_sessions_user_uuid'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_admin_settings_category', table_name='admin_configurations')
    op.drop_index(op.f('ix_admin_configurations_key'), table_name='admin_configurations')
    op.drop_table('admin_configurations')
    # ### end Alembic commands ###
