"""add_customer_name_location_name_to_borrow_requests

Revision ID: e4d2d73aefba
Revises: 0ef47b079095
Create Date: 2026-03-19 10:03:54.420366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d2d73aefba'
down_revision: Union[str, Sequence[str], None] = '0ef47b079095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_requests', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('borrow_requests', sa.Column('location_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_requests', 'location_name')
    op.drop_column('borrow_requests', 'customer_name')
    # ### end Alembic commands ###
