"""refactoring models

Revision ID: ea9c8155861e
Revises: 71039f428438
Create Date: 2026-03-14 23:00:45.347090

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ea9c8155861e'
down_revision: Union[str, Sequence[str], None] = '71039f428438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
