"""added fk constraint on users-inventory movement, added quantity constraint on inventory

Revision ID: f2d8856a7b55
Revises: ea9c8155861e
Create Date: 2026-03-15 09:56:48.880308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d8856a7b55'
down_revision: Union[str, Sequence[str], None] = 'ea9c8155861e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('actor_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_inventory_movements_actor_id'), 'inventory_movements', ['actor_id'], unique=False)
    op.create_foreign_key(None, 'inventory_movements', 'users', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movements_actor_id'), table_name='inventory_movements')
    op.drop_column('inventory_movements', 'actor_id')
    # ### end Alembic commands ###
