"""add device_id to session tables

Revision ID: faefa4806d55
Revises: 398648b96f64
Create Date: 2026-03-29 19:39:00.881452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faefa4806d55'
down_revision: Union[str, Sequence[str], None] = '398648b96f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrower_sessions', sa.Column('device_id', sa.String(length=100), nullable=True))
    op.add_column('user_sessions', sa.Column('device_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'device_id')
    op.drop_column('borrower_sessions', 'device_id')
    # ### end Alembic commands ###
