"""updating inventory schemas

Revision ID: fb640816bdff
Revises: 8a2b7f14c9d1
Create Date: 2026-04-09 15:01:22.153243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb640816bdff'
down_revision: Union[str, Sequence[str], None] = '8a2b7f14c9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrow_requests', 'borrower_signature',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('inventory', sa.Column('total_qty', sa.Integer(), nullable=False))
    op.add_column('inventory', sa.Column('available_qty', sa.Integer(), nullable=False))
    op.add_column('inventory', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('inventory', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'description')
    op.drop_column('inventory', 'status')
    op.drop_column('inventory', 'available_qty')
    op.drop_column('inventory', 'total_qty')
    op.alter_column('borrow_requests', 'borrower_signature',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
